/* Make use of go's powerful duck-typing, rather than base-class mimicry
 *
 * This file would be auto-generated by antlr.
 * Though the user would have to specify what type replaces Node as the return value.
 */
package main

import "github.com/dragonfax/java_converter/parser"

type HasAggregator interface {
	Aggregator(aggregate, next Node) Node
}

type HasVisitVariableDeclaratorId interface {
	VisitVariableDeclaratorId(ctx *parser.VariableDeclaratorIdContext) Node
}

type HasVisitFieldDeclaraction interface {
	VisitFieldDeclaraction(ctx *parser.FieldDeclarationContext) Node
}

type HasVisitClassDeclaration interface {
	VisitClassDeclaration(ctx *parser.ClassDeclarationContext) Node
}

type HasVisitTypeType interface {
	VisitTypeType(ctx *parser.TypeTypeContext) Node
}
